/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2021-10-08 05:43:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage.account.admin_005fmanage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import com.spk.common.constant.CommonConstant;
import com.spk.type.*;
import com.spk.util.Util;
import com.spk.util.DbUtil;
import java.util.HashMap;
import com.spk.common.constant.CommonConstant;
import com.spk.type.*;
import com.spk.util.Util;
import com.spk.util.DbUtil;
import com.spk.type.*;

public final class manage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/include/dialog/confirm-dialog.jsp", Long.valueOf(1623113786000L));
    _jspx_dependants.put("/manage/account/admin_manage/changeadminpassword-dialog.jsp", Long.valueOf(1623113789000L));
    _jspx_dependants.put("/manage/account/admin_manage/managebody.jsp", Long.valueOf(1623113789000L));
    _jspx_dependants.put("/top.jsp", Long.valueOf(1625118829000L));
    _jspx_dependants.put("/include/dialog/alert-dialog.jsp", Long.valueOf(1623113786000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
	response.setHeader("Pragma","no-cache"); //HTTP 1.0
	response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

	String webTitle = CommonConstant.SERVER_TITLE;
	/*************************************************************************
	 * 서버 설정 정보 조회
	 ************************************************************************/
	 HashMap<String, String> mapServerConfig = DbUtil.getServerConfig(session);
	if (!mapServerConfig.isEmpty()) {
		if ("MEDISAFER".equals(mapServerConfig.get("oem").toUpperCase())) {
			webTitle = CommonConstant.MEDISAFER_SERVER_TITLE;
		} else if ("BIZSAFER".equals(mapServerConfig.get("oem").toUpperCase())) {
			webTitle = CommonConstant.BIZSAFER_SERVER_TITLE;
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"ko\" lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE9\" />\r\n");
      out.write("\t<meta http-equiv=\"Expires\" content=\"-1\" />\r\n");
      out.write("\t<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" content=\"No-Cache\" />\r\n");
      out.write("\t<title>");
      out.print(webTitle);
      out.write("</title>\r\n");
      out.write("\r\n");
 if ("darkness".equals((String)session.getAttribute("THEMENAME"))) { 
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/darkness.css\" media=\"all\" />\r\n");
 } else { 
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/default.css\" media=\"all\" />\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
 if ("darkness".equals((String)session.getAttribute("THEMENAME"))) { 
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/jquery-ui-1.10.3/themes/darkness/jquery.ui.all.css\" media=\"all\" />\r\n");
 } else { 
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/jquery-ui-1.10.3/css/custom-theme/jquery-ui-1.10.3.custom.css\" media=\"all\" />\r\n");
 } 
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery-ui-1.10.3/js/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/scrollbar/jquery.mCustomScrollbar.css\" media=\"all\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/scrollbar/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/jquery-ui-layout/layout-default-latest.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery-ui-layout/jquery.layout-latest.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/menu/css/dcmegamenu.css\" media=\"all\" />\r\n");
 if ("darkness".equals((String)session.getAttribute("THEMENAME"))) { 
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/menu/css/skins/black.css\" media=\"all\" />\r\n");
 } else { 
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/menu/css/skins/black.css\" media=\"all\" />\r\n");
 } 
      out.write("\r\n");
      out.write("\t<script type='text/javascript' src=\"/js/menu/js/jquery.hoverIntent.minified.js\"></script>\r\n");
      out.write("\t<script type='text/javascript' src=\"/js/menu/js/jquery.dcmegamenu.1.3.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/blockui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jshashtable-2.1/jshashtable.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/checkparam.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/commparam.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/types.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/layout.css\" media=\"all\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/layout.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\touterLayout = $(\"body\").layout(outerDefaultLayoutOptions);\r\n");
      out.write("\t\t\tshowInnerLayout(\"innerDefault\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\treloadDefaultLayout = function() {\r\n");
      out.write("\t\t\t$('.inner-center .ui-layout-content').mCustomScrollbar('update');\r\n");
      out.write("\t\t};\r\n");
      out.write("\t//-->\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"ui-layout-north\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar g_objAlertDialog;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tg_objAlertDialog = $('#dialog-alert');\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.dialog({\r\n");
      out.write("\t\t\tautoOpen: false,\r\n");
      out.write("\t\t\tresizable: false,\r\n");
      out.write("\t\t\twidth: 500,\r\n");
      out.write("\t\t\theight: 'auto',\r\n");
      out.write("\t\t\tcloseOnEscape: false,\r\n");
      out.write("\t\t\tmodal: true,\r\n");
      out.write("\t\t\topen: function() {\r\n");
      out.write("\t\t\t\t$(this).parent().find('.ui-dialog-buttonpane button:contains(\"확인\")').button({\r\n");
      out.write("\t\t\t\t\ticons: { primary: 'ui-icon-circle-check' }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).parent().find(\".ui-dialog-titlebar-close\").hide();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbuttons: {\r\n");
      out.write("\t\t\t\t\"확인\": function() {\r\n");
      out.write("\t\t\t\t\t$(this).dialog('close');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tdisplayInfoDialog = function(dialogTitle, infoTitle, infoMessage) {\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-div').hasClass('ui-state-error')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-div').removeClass('ui-state-error').addClass('ui-state-highlight');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-icon').hasClass('ui-icon-alert')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-icon').removeClass('ui-icon-alert').addClass('ui-icon-info');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-title').html(infoTitle);\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-message').html(infoMessage);\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.dialog('option', 'title', dialogTitle);\r\n");
      out.write("\t\tg_objAlertDialog.dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdisplayAlertDialog = function(dialogTitle, alertTitle, alertMessage) {\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-div').hasClass('ui-state-highlight')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-div').removeClass('ui-state-highlight').addClass('ui-state-error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-icon').hasClass('ui-icon-info')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-icon').removeClass('ui-icon-info').addClass('ui-icon-alert');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-title').html(alertTitle);\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-message').html(alertMessage);\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.dialog('option', 'title', dialogTitle);\r\n");
      out.write("\t\tg_objAlertDialog.dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"dialog-alert\" title=\"\" class=\"dialog-form\">\r\n");
      out.write("\t<div id=\"alert-div\" class=\"ui-state-highlight\" style=\"padding: 10px 10px 5px 10px;\">\r\n");
      out.write("\t\t<div class=\"icon-message-holder\">\r\n");
      out.write("\t\t\t<div class=\"icon-holder\"><span id=\"alert-icon\" class=\"ui-icon ui-icon-info\"></span></div>\r\n");
      out.write("\t\t\t<div class=\"message-holder\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-message\"><strong><span id=\"alert-title\"></span></strong></div>\r\n");
      out.write("\t\t\t\t<div class=\"detail-message\"><span id=\"alert-message\"></span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

String serverTypeString = "";
String versionString = "1.0.0.0";
String imageTitle = "top_logo_spk.png";
String oemString = "";
String webTitleString = CommonConstant.SERVER_TITLE;

//****************************************************************************
// 관리자의 로그인 상태 정보를 읽어옴
//****************************************************************************
HashMap<String, String> mapLoginStatus = DbUtil.getAdminLoginStatus(session);
if (!mapLoginStatus.isEmpty()) {
	//************************************************************************
	// 사업장 생성이후 최초 관리자 로그인시 main.jsp에서 랜딩 설정 Dialog 팝업
	//************************************************************************
	if (OptionType.OPTION_TYPE_NO.equals((String) session.getAttribute("ISFIRSTLOGINADMINOFCOMPANY"))) {
		//************************************************************************
		// 관리자 생성 후 비밀번호를 변경하지 않은 관리자인 경우 - 비밀번호 변경 페이지로 이동
		//************************************************************************
		if (!AdminType.ADMIN_TYPE_SITE_ADMIN.equals((String) session.getAttribute("ADMINTYPE")) &&
				ChangeFirstPasswordState.CHANGE_FIRST_PASSWORD_STATE_NONE.equals((String) session.getAttribute("CHANGEFIRSTPASSWORDFLAG"))) {
			if (!request.getRequestURI().equals("/manage/account/admin_manage/manage.jsp")) {
				response.sendRedirect("/manage/account/admin_manage/manage.jsp");
			}
		}

		//************************************************************************
		// 비밀번호 유효기간이 만료된 경우 - 비밀번호 변경 페이지로 이동
		//************************************************************************
		if (OptionType.OPTION_TYPE_YES.equals((String) session.getAttribute("NEEDCHANGEPASSWORDFLAG"))) {
			if (!request.getRequestURI().equals("/manage/account/admin_manage/manage.jsp")) {
				response.sendRedirect("/manage/account/admin_manage/manage.jsp");
			}
		}
	}

	//************************************************************************
	// 서버 정보를 읽어옴
	//************************************************************************
	HashMap<String, String> mapTopServerConfig = DbUtil.getServerConfig(session);
	if (!mapTopServerConfig.isEmpty()) {
		ServerType serverType = new ServerType();
		serverTypeString = serverType.getTypeValue(mapTopServerConfig.get("servertype"));
		versionString = mapTopServerConfig.get("version");
		oemString = mapTopServerConfig.get("oem").toUpperCase();
		if ("MEDISAFER".equals(oemString)) {
			webTitleString = CommonConstant.MEDISAFER_SERVER_TITLE;
			imageTitle = "top_logo_medisafer.png";
		} else if ("BIZSAFER".equals(oemString)) {
			webTitleString = CommonConstant.BIZSAFER_SERVER_TITLE;
			imageTitle = "top_logo_bizsafer.png";
		}
	}
} else {
	response.sendRedirect("/login/login.jsp");
}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tdocument.title = \"");
      out.print(webTitleString);
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("// \tif (session.getId().equals(mapLoginStatus.get(\"loginsessionid\"))) {\r\n");
      out.write("// \t\tif (!LoginState.LOGIN_STATE_LOGIN.equals(mapLoginStatus.get(\"loginflag\"))) {\r\n");
      out.write("// \talert(\"연결이 종료되었습니다. 다시 접속해 주세요.\");\r\n");
      out.write("// \tlocation.href = \"/login/login.jsp\";\r\n");
      out.write("// \t\t}\r\n");
      out.write("// \t} else {\r\n");
      out.write("// \t\tif (LoginState.LOGIN_STATE_FORCED_LOGOUT.equals(mapLoginStatus.get(\"loginflag\"))) {\r\n");
      out.write("// \talert(\"다른 관리자의 접속으로 현재의 연결이 종료되었습니다.\");\r\n");
      out.write("// \tlocation.href = \"/login/login.jsp\";\r\n");
      out.write("// \t\t} else {\r\n");
      out.write("// \talert(\"연결이 종료되었습니다. 다시 접속해 주세요.\");\r\n");
      out.write("// \tlocation.href = \"/login/login.jsp\";\r\n");
      out.write("// \t\t}\r\n");
      out.write("// \t}\r\n");
      out.write("\r\n");
      out.write("\tvar g_timeoutHandle;\r\n");
      out.write("\tvar g_isWorking = false;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function($){\r\n");
      out.write("\t\tsetBrowserTimeout();\r\n");
      out.write("\r\n");
      out.write("\t\t$(window.document).click( function() {\r\n");
      out.write("\t\t\tclearBrowserTimeout();\r\n");
      out.write("\t\t\tsetBrowserTimeout();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tshowMenu();\r\n");
      out.write("\r\n");
      out.write("\t\twindow.onbeforeunload = function () {\r\n");
      out.write("\t\t\tif (isBrowserClosed()) {\r\n");
      out.write("\t\t\t\tlogout();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t$('button[name=\"btnHelp\"]').button({ icons: {primary: \"ui-icon-disk\"} });\r\n");
      out.write("\r\n");
      out.write("\t\t$('#btnLogout').click(function() {\r\n");
      out.write("\t\t\tlogout();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
 if ("darkness".equals((String) session.getAttribute("THEMENAME"))) { 
      out.write("\r\n");
      out.write("\t\t$('select[name=\"selecttheme\"] option[value=\"darkness\"]').prop(\"selected\", \"selected\");\r\n");
 } else { 
      out.write("\r\n");
      out.write("\t\t$('select[name=\"selecttheme\"] option[value=\"default\"]').prop(\"selected\", \"selected\");\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t$('select[name=\"selecttheme\"]').change( function() {\r\n");
      out.write("\t\t\tchangeTheme($(this).val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tshowMenu = function() {\r\n");
      out.write("\t\tvar rowItemsCount = '1';\r\n");
      out.write("\t\tvar maximizeWidth = false;\r\n");
      out.write("\t\tif ($(window).height() < 800) {\r\n");
      out.write("\t\t\trowItemsCount = '4';\r\n");
      out.write("\t\t\t//maximizeWidth = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$('#mega-menu-1').show();\r\n");
      out.write("\t\t$('#mega-menu-1').dcMegaMenu({\r\n");
      out.write("\t\t\trowItems: rowItemsCount,\r\n");
      out.write("\t\t\tfullWidth: maximizeWidth,\r\n");
      out.write("\t\t\tspeed: 'fast',\r\n");
      out.write("\t\t\teffect: 'fade',\r\n");
      out.write("\t\t\tfullWidth: false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tisBrowserClosed = function() {\r\n");
      out.write("\t\tvar browserWindowWidth = 0;\r\n");
      out.write("\t\t//var browserWindowHeight = 0;\r\n");
      out.write("\r\n");
      out.write("\t\t// gets the width and height of the browser window\r\n");
      out.write("\t\tif (parseInt(navigator.appVersion) > 3) {\r\n");
      out.write("\t\t\tif (navigator.appName == \"Netscape\") {\r\n");
      out.write("\t\t\t\tbrowserWindowWidth = window.innerWidth;\r\n");
      out.write("\t\t\t\t//browserWindowHeight = window.innerHeight;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (navigator.appName.indexOf(\"Microsoft\") !=- 1) {\r\n");
      out.write("\t\t\t\tbrowserWindowWidth = top.window.document.body.offsetWidth;\r\n");
      out.write("\t\t\t\t//browserWindowHeight = top.window.document.body.offsetHeight;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// checks if the X button was closed\r\n");
      out.write("\t\t// if event.clientY < 0, then click was on the browser menu area\r\n");
      out.write("\t\t// if event.screenX > (browserWindowWidth - 25), the X button was clicked\r\n");
      out.write("\t\t// use screenX if working with multiple frames\r\n");
      out.write("\r\n");
      out.write("\t\treturn (event.clientY < 0 && event.screenX > (browserWindowWidth - 25)) ? true : false;\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tsetBrowserTimeout = function() {\r\n");
      out.write("\t\tif (!g_isWorking) {\r\n");
      out.write("\t\t\tg_timeoutHandle = setTimeout(\"logout()\", ");
      out.print(session.getMaxInactiveInterval()*1000);
      out.write(");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tclearBrowserTimeout = function() {\r\n");
      out.write("\t\tclearTimeout(g_timeoutHandle);\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tlogout = function() {\r\n");
      out.write("\t\tlocation.href = \"/login/logout.jsp\";\r\n");
      out.write("\t};\r\n");
      out.write("/*\r\n");
      out.write("\tchangeTheme = function(themeName) {\r\n");
      out.write("\t\tvar postData = getRequestChangeThemeParam(themeName);\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\turl: \"/CommandService\",\r\n");
      out.write("\t\t\tdata: $.param({sendmsg : postData}),\r\n");
      out.write("\t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t\tcache: false,\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tsuccess: function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\tif ($(data).find('errorcode').text() != \"0000\") {\r\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"THEME 변경\", \"THEME 변경 중 오류가 발생하였습니다.\", $(data).find('errormsg').text());\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\twindow.location.reload(true);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tif (jqXHR.status != 0 && jqXHR.readyState != 0) {\r\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"THEME 변경\", \"THEME 변경 중 오류가 발생하였습니다.\", jqXHR.statusText + \"(\" + jqXHR.status + \")\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("*/\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"top_status_bar\">\r\n");
      out.write("\t");
      out.print((String) session.getAttribute("ADMINID"));
      out.write(" 님&nbsp;\r\n");
      out.write("\t<input type=\"button\" id=\"btnLogout\" class=\"logout-button\" value=\"LOGOUT\" />\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"top_menu_bar\">\r\n");
      out.write("\t<div class=\"first_block\">\r\n");
      out.write("\t\t<div class=\"logo-display\">\r\n");
      out.write("\t\t\t<span><a href=\"/main.jsp\" onFocus=\"this.blur();\"><img src=\"/images/");
      out.print(imageTitle);
      out.write("\" /></a></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"second_block\">\r\n");
      out.write("\t\t<ul id=\"mega-menu-1\" class=\"mega-menu\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">관리</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">조직 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/organization/organization_manage/manage.jsp\">부서/사용자 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/organization/batch_user_regist/manage.jsp\">사용자 배치 등록</a></li>\r\n");
 if (AdminType.ADMIN_TYPE_COMPANY_ADMIN.equals((String) session.getAttribute("ADMINTYPE"))) { 
      out.write('\r');
      out.write('\n');
      out.write('	');
 if ("TRUE".equals(session.getServletContext().getInitParameter("activate_user_synchronization").toUpperCase())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/organization/user_synchronization/manage.jsp\">사용자 동기화</a></li>\r\n");
      out.write("\t");
 } 
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 if (AdminType.ADMIN_TYPE_COMPANY_ADMIN.equals((String) session.getAttribute("ADMINTYPE"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사업장/계정 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/account/company_manage/manage.jsp\">사업장 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/account/admin_manage/manage.jsp\">계정 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">공지 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/user_notice/user_notice_manage/manage.jsp\">사용자 공지</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 if ((session.getAttribute("DBPROTECTIONOPTION") == null) || SupportFunctionType.SUPPORT_FUNCTION_TYPE_ACTIVATE.equals((String) session.getAttribute("DBPROTECTIONOPTION"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">DB 보안 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/db_protection/db_protection_manage/manage.jsp\">DB 보안 설정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/db_protection/db_protection_log/list.jsp\">DB 보안 로그</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 } else if (SupportFunctionType.SUPPORT_FUNCTION_TYPE_DEACTIVATE.equals((String) session.getAttribute("DBPROTECTIONOPTION"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">DB 보안 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);.jsp\" class=\"disabled\">DB 보안 설정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">DB 보안 로그</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 } 
      out.write('\r');
      out.write('\n');
 if ((session.getAttribute("SOFTWAREMANAGEOPTION") == null) || SupportFunctionType.SUPPORT_FUNCTION_TYPE_ACTIVATE.equals((String) session.getAttribute("SOFTWAREMANAGEOPTION"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">소프트웨어 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/software/software_installation/softwareinstallationperorganizationlist.jsp\">조직별 설치 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manage/software/software_installation/softwareinstallationpersoftwarelist.jsp\">소프트웨어별 설치 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 } else if (SupportFunctionType.SUPPORT_FUNCTION_TYPE_DEACTIVATE.equals((String) session.getAttribute("SOFTWAREMANAGEOPTION"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">소프트웨어 관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">조직별 설치 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">소프트웨어별 설치 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">설정</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">에이전트</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/config/agent/agent_config/manage.jsp\">에이전트 설정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/config/agent/agent_config_status/list.jsp\">에이전트 설정 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">검사</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/config/search/force_search/manage.jsp\">강제검사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/config/search/reserve_search/manage.jsp\">예약검사</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">결재</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/config/approval/approvator_manage/manage.jsp\">결재자 설정</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"display: none;\"><a href=\"#\">문서보안 권한</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/config/drm_permission/drm_permission_policy/manage.jsp\">정책 설정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/config/drm_permission/user_belongs_drm_permission_policy_status/list.jsp\">사용자별 소속 정책 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">조회</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">에이전트</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/search/agent/user_log/list.jsp\">사용자 로그</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">개인정보</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/search/privacy/search_log/list.jsp\">검사 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/search/privacy/detect_log/list.jsp\">검출 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/search/privacy/realtime_observation_log/list.jsp\">실시간 파일 감시 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 if (((session.getAttribute("MEDIACONTROLOPTION") == null) || SupportFunctionType.SUPPORT_FUNCTION_TYPE_ACTIVATE.equals((String) session.getAttribute("MEDIACONTROLOPTION"))) ||
		((session.getAttribute("NETWORKSERVICECONTROLOPTION") == null) || SupportFunctionType.SUPPORT_FUNCTION_TYPE_ACTIVATE.equals((String) session.getAttribute("NETWORKSERVICECONTROLOPTION")))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">정보 유출 방지</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
 if (((session.getAttribute("MEDIACONTROLOPTION") == null) || SupportFunctionType.SUPPORT_FUNCTION_TYPE_ACTIVATE.equals((String) session.getAttribute("MEDIACONTROLOPTION"))) ||
		((session.getAttribute("NETWORKSERVICECONTROLOPTION") == null) || SupportFunctionType.SUPPORT_FUNCTION_TYPE_ACTIVATE.equals((String) session.getAttribute("NETWORKSERVICECONTROLOPTION")))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/search/media_control/media_control_log/list.jsp\">매체/네트워크 제어 내역</a></li>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/search/url_block/url_block_log/list.jsp\">URL 차단 내역</a></li> -->\r\n");
 } else if ((SupportFunctionType.SUPPORT_FUNCTION_TYPE_DEACTIVATE.equals((String) session.getAttribute("MEDIACONTROLOPTION"))) &&
		(SupportFunctionType.SUPPORT_FUNCTION_TYPE_DEACTIVATE.equals((String) session.getAttribute("NETWORKSERVICECONTROLOPTION")))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">매체/네트워크 제어 내역</a></li>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">URL 차단 내역</a></li> -->\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">결재</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/search/approval/approval_status/list.jsp\">결재 목록</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">안전반출</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/search/safe_export/safe_export_staus/list.jsp\">안전반출 목록</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</li> -->\r\n");
 if ("MEDISAFER".equalsIgnoreCase(oemString) || "BIZSAFER".equalsIgnoreCase(oemString)) { 
      out.write('\r');
      out.write('\n');
      out.write('	');
 if ((session.getAttribute("RANSOMWAREDETECTIONOPTION") == null) || SupportFunctionType.SUPPORT_FUNCTION_TYPE_ACTIVATE.equals((String) session.getAttribute("RANSOMWAREDETECTIONOPTION"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">랜섬웨어</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/search/ransomware/ransomware_detect_log/list.jsp\">검출 목록</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t");
 } else if (SupportFunctionType.SUPPORT_FUNCTION_TYPE_DEACTIVATE.equals((String) session.getAttribute("RANSOMWAREDETECTIONOPTION"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">랜섬웨어</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">검출 목록</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t");
 } 
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li style=\"display: none;\"><a href=\"#\">문서보안 권한</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/search/drm_permission/drm_permission_settings_log/list.jsp\">설정 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">출력</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/search/print/print_log/list.jsp\">출력 목록</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">출력</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">출력 목록</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">통계</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">에이전트</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/agent/agent_install_status/status.jsp\">에이전트 설치 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">개인정보</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/privacy/search_status_per_terms/status.jsp\">기간별 검사 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/privacy/detect_status_per_terms/status.jsp\">기간별 검출 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/privacy/pattern_detect_status_per_organization/status.jsp\">조직별 패턴 검출 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/privacy/filetype_detect_status_per_organization/status.jsp\">조직별 파일 유형 검출 현황</a></li>\r\n");
 if (AdminType.ADMIN_TYPE_SITE_ADMIN.equals((String) session.getAttribute("ADMINTYPE"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/privacy/company_detect_status_per_pattern/status.jsp\">패턴별 사업장 검출 현황</a></li>\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/privacy/dept_detect_status_per_pattern/status.jsp\">패턴별 부서 검출 현황</a></li>\r\n");
 if (AdminType.ADMIN_TYPE_SITE_ADMIN.equals((String) session.getAttribute("ADMINTYPE"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/privacy/company_detect_status_per_filetype/status.jsp\">파일 유형별 사업장 검출 현황</a></li>\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/privacy/dept_detect_status_per_filetype/status.jsp\">파일 유형별 부서 검출 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">안전반출</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/statistics/safe_export/safe_export_status_per_terms/status.jsp\">기간별 반출 현황</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</li> -->\r\n");
 if ("MEDISAFER".equalsIgnoreCase(oemString) || "BIZSAFER".equalsIgnoreCase(oemString)) { 
      out.write('\r');
      out.write('\n');
      out.write('	');
 if ((session.getAttribute("RANSOMWAREDETECTIONOPTION") == null) || SupportFunctionType.SUPPORT_FUNCTION_TYPE_ACTIVATE.equals((String) session.getAttribute("RANSOMWAREDETECTIONOPTION"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">랜섬웨어</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/statistics/ransomware/ransomware_detect_status_per_terms/status.jsp\">기간별 검출 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t");
 } else if (SupportFunctionType.SUPPORT_FUNCTION_TYPE_DEACTIVATE.equals((String) session.getAttribute("RANSOMWAREDETECTIONOPTION"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">랜섬웨어</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">기간별 검출 목록</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t");
 } 
      out.write('\r');
      out.write('\n');
 } 
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">출력</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/statistics/print/print_status_per_terms/status.jsp\">기간별 출력 현황</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">출력</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">기간별 출력 현황</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">리포트</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">개인정보</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/report/privacy/user_not_executed_search/list.jsp\">검사 미실행 사용자 목록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/report/privacy/detect_status_per_user/list.jsp\">사용자별 검출 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/report/privacy/detect_status_per_dept/list.jsp\">부서별 검출 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/report/privacy/detect_file_list/list.jsp\">검출 파일 목록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/report/privacy/detect_file_process_status_per_user/list.jsp\">사용자별 검출 파일 처리 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/report/privacy/detect_file_process_status_per_dept/list.jsp\">부서별 검출 파일 처리 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">안전반출</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/report/safe_export/safe_export_status_per_user/list.jsp\">사용자별 반출 현황</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/report/safe_export/safe_export_status_per_dept/list.jsp\">부서별 반출 현황</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">프린트</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/report/print/print_status_per_user/list.jsp\">사용자별 출력 현황</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/report/print/print_status_per_dept/list.jsp\">부서별 출력 현황</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">프린트</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">사용자별 출력 현황</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" class=\"disabled\">부서별 출력 현황</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">보안정책 현황</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/report/security_status/monthly_report/list.jsp\">월별 보안정책 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">모니터링</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">에이전트</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/monitor/agent/agent_access_status/list.jsp\">사용자 접속 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/monitor/agent/agent_system_status/list.jsp\">사용자 시스템 현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 if (AdminType.ADMIN_TYPE_SITE_ADMIN.equals((String) session.getAttribute("ADMINTYPE"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">서버</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/monitor/server/server_system_status/status.jsp\">서버 시스템 정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
 if (AdminType.ADMIN_TYPE_SITE_ADMIN.equals((String) session.getAttribute("ADMINTYPE"))) { 
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"#\">사이트 관리</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t");
 if (ServerType.SERVER_TYPE_ASP.equals((String) session.getAttribute("SERVERTYPE"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">서비스</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/service/application/manage.jsp\">서비스 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사업장</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/company/company_manage/manage.jsp\">사업장 관리</a></li>\r\n");
      out.write("\t");
 if (ServerType.SERVER_TYPE_ASP.equals((String) session.getAttribute("SERVERTYPE"))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/licence/licence_manage/manage.jsp\">라이센스 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/licence/licence_renewal_history/list.jsp\">라이센스 갱신 목록</a></li>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li><a href=\"/site_manage/payment/payment_history/list.jsp\">결제 내역 목록</a></li> -->\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">관리자</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/admin/admin_manage/manage.jsp\">관리자 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/admin/admin_log/list.jsp\">관리자 로그</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">패턴</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/pattern/pattern_manage/manage.jsp\">패턴 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">네트워크</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/media_control/network_service_control_program/manage.jsp\">서비스 제어 프로그램 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 if ("MEDISAFER".equalsIgnoreCase(oemString) || "BIZSAFER".equalsIgnoreCase(oemString)) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">랜섬웨어</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/ransomware/ransomware_credential_exception_manage/manage.jsp\">신뢰정보 예외 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/ransomware/ransomware_behavior_profile_exception_manage/manage.jsp\">행위분석 예외 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">API</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/api/api_callable_address_manage/manage.jsp\">API 호출 가능 주소 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">에이전트</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/site_manage/agent/agent_update_manage/manage.jsp\">업데이트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
 } 
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t<div class=\"site-map-path\"> -->\r\n");
      out.write("<!-- \t\t\t<ul class=\"ui-helper-clearfix icons\"><li><span class=\"ui-icon ui-icon-folder-open\"></span></li></ul> -->\r\n");
      out.write("<!-- \t\t\t<span class=\"parent-path\">관리</span> -->\r\n");
      out.write("<!-- \t\t\t<ul class=\"ui-helper-clearfix icons\"><li><span class=\"ui-icon ui-icon-carat-1-e\"></span></li></ul> -->\r\n");
      out.write("<!-- \t\t\t<span class=\"parent-path\">계정/사업장 관리자</span> -->\r\n");
      out.write("<!-- \t\t\t<ul class=\"ui-helper-clearfix icons\"><li><span class=\"ui-icon ui-icon-carat-1-e\"></span></li></ul> -->\r\n");
      out.write("<!-- \t\t\t<span class=\"current-path\">계정 관리</span> -->\r\n");
      out.write("<!-- \t\t</div> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"ui-layout-center\">\r\n");
      out.write("\t\t<div id=\"innerDefault\" class=\"inner-layout-container\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar g_objAlertDialog;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tg_objAlertDialog = $('#dialog-alert');\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.dialog({\r\n");
      out.write("\t\t\tautoOpen: false,\r\n");
      out.write("\t\t\tresizable: false,\r\n");
      out.write("\t\t\twidth: 500,\r\n");
      out.write("\t\t\theight: 'auto',\r\n");
      out.write("\t\t\tcloseOnEscape: false,\r\n");
      out.write("\t\t\tmodal: true,\r\n");
      out.write("\t\t\topen: function() {\r\n");
      out.write("\t\t\t\t$(this).parent().find('.ui-dialog-buttonpane button:contains(\"확인\")').button({\r\n");
      out.write("\t\t\t\t\ticons: { primary: 'ui-icon-circle-check' }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).parent().find(\".ui-dialog-titlebar-close\").hide();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbuttons: {\r\n");
      out.write("\t\t\t\t\"확인\": function() {\r\n");
      out.write("\t\t\t\t\t$(this).dialog('close');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tdisplayInfoDialog = function(dialogTitle, infoTitle, infoMessage) {\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-div').hasClass('ui-state-error')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-div').removeClass('ui-state-error').addClass('ui-state-highlight');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-icon').hasClass('ui-icon-alert')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-icon').removeClass('ui-icon-alert').addClass('ui-icon-info');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-title').html(infoTitle);\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-message').html(infoMessage);\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.dialog('option', 'title', dialogTitle);\r\n");
      out.write("\t\tg_objAlertDialog.dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdisplayAlertDialog = function(dialogTitle, alertTitle, alertMessage) {\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-div').hasClass('ui-state-highlight')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-div').removeClass('ui-state-highlight').addClass('ui-state-error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-icon').hasClass('ui-icon-info')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-icon').removeClass('ui-icon-info').addClass('ui-icon-alert');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-title').html(alertTitle);\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-message').html(alertMessage);\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.dialog('option', 'title', dialogTitle);\r\n");
      out.write("\t\tg_objAlertDialog.dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"dialog-alert\" title=\"\" class=\"dialog-form\">\r\n");
      out.write("\t<div id=\"alert-div\" class=\"ui-state-highlight\" style=\"padding: 10px 10px 5px 10px;\">\r\n");
      out.write("\t\t<div class=\"icon-message-holder\">\r\n");
      out.write("\t\t\t<div class=\"icon-holder\"><span id=\"alert-icon\" class=\"ui-icon ui-icon-info\"></span></div>\r\n");
      out.write("\t\t\t<div class=\"message-holder\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-message\"><strong><span id=\"alert-title\"></span></strong></div>\r\n");
      out.write("\t\t\t\t<div class=\"detail-message\"><span id=\"alert-message\"></span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar g_objConfirmDialog;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tg_objConfirmDialog = $('#dialog-confirm');\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tdisplayConfirmDialog = function(dialogTitle, confirmTitle, confirmMessage, funcToExec) {\r\n");
      out.write("\t\tg_objConfirmDialog.dialog({\r\n");
      out.write("\t\t\tautoOpen: false,\r\n");
      out.write("\t\t\tresizable: false,\r\n");
      out.write("\t\t\twidth: 500,\r\n");
      out.write("\t\t\theight: 'auto',\r\n");
      out.write("\t\t\tcloseOnEscape: false,\r\n");
      out.write("\t\t\tmodal: true,\r\n");
      out.write("\t\t\topen: function() {\r\n");
      out.write("\t\t\t\t$(this).parent().find('.ui-dialog-buttonpane button:contains(\"확인\")').button({\r\n");
      out.write("\t\t\t\t\ticons: { primary: 'ui-icon-circle-check' }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).parent().find('.ui-dialog-buttonpane button:contains(\"취소\")').button({\r\n");
      out.write("\t\t\t\t\ticons: { primary: 'ui-icon-circle-close' }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).parent().find(\".ui-dialog-titlebar-close\").hide();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbuttons: {\r\n");
      out.write("\t\t\t\t\"확인\": function() {\r\n");
      out.write("\t\t\t\t\tfuncToExec();\r\n");
      out.write("\t\t\t\t\t$(this).dialog('close');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"취소\": function() {\r\n");
      out.write("\t\t\t\t\t$(this).dialog('close');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tg_objConfirmDialog.find('#confirm-title').html(confirmTitle);\r\n");
      out.write("\t\tg_objConfirmDialog.find('#confirm-message').html(confirmMessage);\r\n");
      out.write("\t\tg_objConfirmDialog.dialog('option', 'title', dialogTitle);\r\n");
      out.write("\r\n");
      out.write("\t\tg_objConfirmDialog.dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"dialog-confirm\" title=\"\" class=\"dialog-form\">\r\n");
      out.write("\t<div style=\"padding: 10px 10px 5px 10px;\">\r\n");
      out.write("\t\t<div class=\"icon-message-holder\">\r\n");
      out.write("\t\t\t<div class=\"icon-holder\"><span id=\"alert-icon\" class=\"ui-icon ui-icon-circle-check\"></span></div>\r\n");
      out.write("\t\t\t<div class=\"message-holder\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-message\"><strong><span id=\"confirm-title\"></span></strong></div>\r\n");
      out.write("\t\t\t\t<div class=\"detail-message\"><span id=\"confirm-message\"></span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("\tvar g_objChangeAdminPasswordDialog;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tg_objChangeAdminPasswordDialog = $('#dialog-changeadminpassword');\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\topenChangeAdminPasswordDialog = function() {\r\n");
      out.write("\r\n");
      out.write("\t\tg_objChangeAdminPasswordDialog.find('#adminid').text(g_objAdminInfo.find('#adminid').text());\r\n");
      out.write("\t\tg_objChangeAdminPasswordDialog.find('#adminname').text(g_objAdminInfo.find('input[name=\"adminname\"]').val());\r\n");
      out.write("\r\n");
      out.write("\t\tg_objChangeAdminPasswordDialog.dialog({\r\n");
      out.write("\t\t\tautoOpen: false,\r\n");
      out.write("\t\t\twidth: 400,\r\n");
      out.write("\t\t\tmaxWidth: $(document).width(),\r\n");
      out.write("\t\t\theight: 'auto',\r\n");
      out.write("\t\t\tmaxHeight: $(document).height(),\r\n");
      out.write("\t\t\tresizable: false,\r\n");
      out.write("\t\t\tmodal: true,\r\n");
      out.write("\t\t\topen: function() {\r\n");
      out.write("\t\t\t\t$(this).parent().find('.ui-dialog-buttonpane button:contains(\"비밀번호 변경\")').button({\r\n");
      out.write(" \t\t\t\t\ticons: { primary: 'ui-icon-key' }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).parent().find('.ui-dialog-buttonpane button:contains(\"취소\")').button({\r\n");
      out.write(" \t\t\t\t\ticons: { primary: 'ui-icon-circle-close' }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).parent().find(\".ui-dialog-titlebar-close\").hide();\r\n");
      out.write("\t\t\t\t$(this).parent().focus();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbuttons: {\r\n");
      out.write("\t\t\t\t\"비밀번호 변경\": function() {\r\n");
      out.write("\t\t\t\t\tif (validateChangeAdminPasswordData()) {\r\n");
      out.write("\t\t\t\t\t\tdisplayConfirmDialog(\"계정 비밀번호 변경\", \"계정 비밀번호를 변경하시겠습니까?\", \"\", function() { changePassword(); });\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"취소\": function() {\r\n");
      out.write("\t\t\t\t\t$(this).dialog('close');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tclose: function() {\r\n");
      out.write("\t\t\t\t$(this).find('#validateTips').text('');\r\n");
      out.write("\t\t\t\t$(this).find('input:password').each(function() {\r\n");
      out.write("\t\t\t\t\t$(this).val('');\r\n");
      out.write("\t\t\t\t\tif ($(this).hasClass('ui-state-error'))\r\n");
      out.write("\t\t\t\t\t\t$(this).removeClass('ui-state-error');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("  \t\tg_objChangeAdminPasswordDialog.dialog('open');\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tchangePassword = function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar postData = getRequestChangeAdminPasswordParam('");
      out.print((String)session.getAttribute("ADMINID"));
      out.write("',\r\n");
      out.write("\t\t\t'");
      out.print((String)session.getAttribute("ADMINID"));
      out.write("',\r\n");
      out.write("\t\t\tg_objChangeAdminPasswordDialog.find('input[name=\"oldpwd\"]').val(),\r\n");
      out.write("\t\t\tg_objChangeAdminPasswordDialog.find('input[name=\"pwd\"]').val());\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\turl: \"/CommandService\",\r\n");
      out.write("\t\t\tdata: $.param({sendmsg : postData}),\r\n");
      out.write("\t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t\tcache: false,\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tsuccess: function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\tif ($(data).find('errorcode').text() != \"0000\") {\r\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"계정 비밀번호 변경\", \"계정 비밀번호 변경 중 오류가 발생하였습니다.\", $(data).find('errormsg').text());\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tdisplayInfoDialog(\"계정 비밀번호 변경\", \"정상 처리되었습니다.\", \"정상적으로 계정 비밀번호가 변경되었습니다.\");\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\tg_objChangeAdminPasswordDialog.dialog('close');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tif (jqXHR.status != 0 && jqXHR.readyState != 0) {\r\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"계정 비밀번호 변경\", \"계정 비밀번호 변경 중 오류가 발생하였습니다.\", jqXHR.statusText + \"(\" + jqXHR.status + \")\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvalidateChangeAdminPasswordData = function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar objOldPwd = g_objChangeAdminPasswordDialog.find('input[name=\"oldpwd\"]');\r\n");
      out.write("\t\tvar objPwd = g_objChangeAdminPasswordDialog.find('input[name=\"pwd\"]');\r\n");
      out.write("\t\tvar objConfirmPwd = g_objChangeAdminPasswordDialog.find('input[name=\"confirmpwd\"]');\r\n");
      out.write("\t\tvar objValidateTips = g_objChangeAdminPasswordDialog.find('#validateTips');\r\n");
      out.write("\r\n");
      out.write("\t\tif (!isValidParam(objOldPwd, PARAM_TYPE_PWD, \"기존 비밀번호\", PARAM_PWD_MIN_LEN, PARAM_PWD_MAX_LEN, objValidateTips)) {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (!isValidParam(objPwd, PARAM_TYPE_PWD, \"변경할 비밀번호\", PARAM_PWD_MIN_LEN, PARAM_PWD_MAX_LEN, objValidateTips)) {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (objPwd.val() != objConfirmPwd.val()) {\r\n");
      out.write("\t\t\tupdateTips(objValidateTips, \"입력한 두 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\tobjPwd.val('');\r\n");
      out.write("\t\t\tobjConfirmPwd.val('');\r\n");
      out.write("\t\t\tobjPwd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (objPwd.val() == objOldPwd.val()) {\r\n");
      out.write("\t\t\tupdateTips(objValidateTips, \"이전 비밀번호와 다른 비밀번호를 입력해 주세요.\");\r\n");
      out.write("\t\t\tobjPwd.val('');\r\n");
      out.write("\t\t\tobjConfirmPwd.val('');\r\n");
      out.write("\t\t\tobjPwd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tif (objPwd.hasClass('ui-state-error'))\r\n");
      out.write("\t\t\t\tobjPwd.removeClass('ui-state-error');\r\n");
      out.write("\t\t\tif (objConfirmPwd.hasClass('ui-state-error'))\r\n");
      out.write("\t\t\t\tobjConfirmPwd.removeClass('ui-state-error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t};\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"dialog-changeadminpassword\" title=\"비밀번호 변경\" class=\"dialog-form\">\r\n");
      out.write("\t<div class=\"dialog-contents\">\r\n");
      out.write("\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t<ul class=\"infolist\">\r\n");
      out.write("\t\t\t\t<li><span class=\"required_field\">(*)</span> 필드는 필수 입력 필드입니다.</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"validateTips\" class=\"validateTips\">\r\n");
      out.write("\t\t\t<div class=\"icon-message-holder\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-holder\"><span id=\"alert-icon\" class=\"ui-icon ui-icon-alert\"></span></div>\r\n");
      out.write("\t\t\t\t<div class=\"message-holder\">\r\n");
      out.write("\t\t\t\t\t<div class=\"icon-message\"><strong>입력오류:</strong>&nbsp;<span id=\"validateMsg\"></span></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-contents\">\r\n");
      out.write("\t\t\t<div id=\"row-adminid\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t<div class=\"field-title\">관리자 ID</div>\r\n");
      out.write("\t\t\t\t<div class=\"field-value\"><span id=\"adminid\"></span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"row-adminname\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t<div class=\"field-title\">관리자 명</div>\r\n");
      out.write("\t\t\t\t<div class=\"field-value\"><span id=\"adminname\"></span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"row-oldpwd\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t<div class=\"field-title\">기존 비밀번호<span class=\"required_field\">*</span></div>\r\n");
      out.write("\t\t\t\t<div class=\"field-value\"><input type=\"password\" id=\"oldpwd\" name=\"oldpwd\" value=\"\" class=\"text ui-widget-content\" /></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"row-pwd\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t<div class=\"field-title\">변경할 비밀번호<span class=\"required_field\">*</span></div>\r\n");
      out.write("\t\t\t\t<div class=\"field-value\"><input type=\"password\" id=\"pwd\" name=\"pwd\" value=\"\" class=\"text ui-widget-content\" /></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"row-confirmpwd\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t<div class=\"field-title\">비밀번호 확인<span class=\"required_field\">*</span></div>\r\n");
      out.write("\t\t\t\t<div class=\"field-value\"><input type=\"password\" id=\"confirmpwd\" name=\"confirmpwd\" value=\"\" class=\"text ui-widget-content\" /></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("\tvar g_objAdminInfo;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tg_objAdminInfo = $('#admin-info');\r\n");
      out.write("\r\n");
      out.write("\t\t$( document).tooltip();\r\n");
      out.write("\r\n");
      out.write("\t\t$('button').button();\r\n");
      out.write("\t\t$('#btnChangePassword').button({ icons: {primary: \"ui-icon-key\"} });\r\n");
      out.write("\t\t$('#btnUpdate').button({ icons: {primary: \"ui-icon-wrench\"} });\r\n");
      out.write("\r\n");
      out.write("\t\t$('#dialog:ui-dialog').dialog('destroy');\r\n");
      out.write("\r\n");
 if ("darkness".equals((String)session.getAttribute("THEMENAME"))) { 
      out.write("\r\n");
      out.write("\t\t$('.inner-center .ui-layout-content').mCustomScrollbar({ theme:\"light-2\", scrollButtons:{ enable:true }, scrollInertia:0, advanced:{ autoScrollOnFocus: false, updateOnContentResize: true, updateOnBrowserResize: true } });\r\n");
 } else { 
      out.write("\r\n");
      out.write("\t\t$('.inner-center .ui-layout-content').mCustomScrollbar({ theme:\"dark-2\", scrollButtons:{ enable:true }, scrollInertia:0, advanced:{ autoScrollOnFocus: false, updateOnContentResize: true, updateOnBrowserResize: true } });\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tloadAdminInfo();\r\n");
      out.write("\r\n");
 if (ChangeFirstPasswordState.CHANGE_FIRST_PASSWORD_STATE_NONE.equals((String)session.getAttribute("CHANGEFIRSTPASSWORDFLAG"))) { 
      out.write("\r\n");
      out.write("\t\tdisplayConfirmDialog(\"비밀번호 변경\", \"최초 로그인 또는 비밀번호 초기화 시에는 보안을 위하여 비밀번호를 변경해야 합니다.\", \"\", function() { openChangeAdminPasswordDialog(); });\r\n");
 } else if (OptionType.OPTION_TYPE_YES.equals((String) session.getAttribute("NEEDCHANGEPASSWORDFLAG"))) { 
      out.write("\r\n");
      out.write("\t\tdisplayConfirmDialog(\"비밀번호 변경\", \"비밀번호 유효기간이 만료되었습니다.\", \"새로운 비밀번호로 변경해주세요.\", function() { openChangeAdminPasswordDialog(); });\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t$('button').click( function () {\r\n");
      out.write("\t\t\tif ($(this).attr('id') == 'btnChangePassword') {\r\n");
      out.write("\t\t\t\topenChangeAdminPasswordDialog();\r\n");
      out.write("\t\t\t} else if ($(this).attr('id') == 'btnUpdate') {\r\n");
      out.write("\t\t\t\tif (validateAdminData()) {\r\n");
      out.write("\t\t\t\t\tdisplayConfirmDialog(\"관리자 정보 변경\", \"관리자 정보를 변경하시겠습니까?\", \"\", function() { updateAdmin(); });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tloadAdminInfo = function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar objAdminName = g_objAdminInfo.find('input[name=\"adminname\"]');\r\n");
      out.write("\t\tvar objEmail = g_objAdminInfo.find('input[name=\"email\"]');\r\n");
      out.write("\t\tvar objPhone = g_objAdminInfo.find('input[name=\"phone\"]');\r\n");
      out.write("\t\tvar objMobilePhone = g_objAdminInfo.find('input[name=\"mobilephone\"]');\r\n");
      out.write("\t\tvar objAdminType = g_objAdminInfo.find('input[name=\"admintype\"]');\r\n");
      out.write("\t\tvar objPasswordExpirationFlag = g_objAdminInfo.find('input[name=\"passwordexpirationflag\"]');\r\n");
      out.write("\t\tvar objPasswordExpirationPeriod = g_objAdminInfo.find('input[name=\"passwordexpirationperiod\"]');\r\n");
      out.write("\r\n");
      out.write("\t\tvar postData = getRequestAdminInfoByIdParam('");
      out.print((String)session.getAttribute("ADMINID"));
      out.write("');\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\turl: \"/CommandService\",\r\n");
      out.write("\t\t\tdata: $.param({sendmsg : postData}),\r\n");
      out.write("\t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t\tcache: false,\r\n");
      out.write("\t\t\t//async: false,\r\n");
      out.write("\t\t\tbeforeSend: function() {\r\n");
      out.write("\t\t\t\t$('.inner-center .ui-layout-content').block({ message: '<div style=\"height:20px;\"><img src=\"/images/processing.gif\" width=\"16\" height=\"16\" style=\"vertical-align: middle;\" /> <span style=\"position:relative; bottom: -1px;line-height: 20px;\">처리중...</span></div>', themedCSS: { margin: '0', padding: '0', 'min-width': '180px', 'width': '25%', height: '42px', backgroundColor: '#fff', border: '1px solid #aaa', color: '#fff', '-webkit-box-shadow': '4px 4px 4px 0px rgba(0,0,0,0.55)', '-moz-box-shadow': '4px 4px 4px 0px rgba(0,0,0,0.55)', 'box-shadow': '4px 4px 4px 0px rgba(0,0,0,0.55)' }, overlayCSS: { backgroundColor:'#000', opacity: .3, cursor: 'wait' }, fadeIn: 0, fadeOut: 0 });\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete: function(jqXHR, textStatus) {\r\n");
      out.write("\t\t\t\t$('.inner-center .ui-layout-content').unblock();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\tif ($(data).find('errorcode').text() != \"0000\") {\r\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"관리자 정보 조회\", \"관리자 정보 조회 중 오류가 발생하였습니다.\", $(data).find('errormsg').text());\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar adminName = $(data).find('adminname').text();\r\n");
      out.write("\t\t\t\tvar email = $(data).find('email').text();\r\n");
      out.write("\t\t\t\tvar phone = $(data).find('phone').text();\r\n");
      out.write("\t\t\t\tvar mobilePhone = $(data).find('mobilephone').text();\r\n");
      out.write("\t\t\t\tvar adminType = $(data).find('admintype').text();\r\n");
      out.write("\t\t\t\tvar passwordExpirationFlag = $(data).find('passwordexpirationflag').text();\r\n");
      out.write("\t\t\t\tvar passwordExpirationPeriod = $(data).find('passwordexpirationperiod').text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tobjAdminName.val(adminName);\r\n");
      out.write("\t\t\t\tobjEmail.val(email);\r\n");
      out.write("\t\t\t\tobjPhone.val(phone);\r\n");
      out.write("\t\t\t\tobjMobilePhone.val(mobilePhone);\r\n");
      out.write("\t\t\t\tobjAdminType.val(adminType);\r\n");
      out.write("\t\t\t\tobjPasswordExpirationFlag.val(passwordExpirationFlag);\r\n");
      out.write("\t\t\t\tobjPasswordExpirationPeriod.val(passwordExpirationPeriod);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('button[name=\"btnChangePassword\"]').show();\r\n");
      out.write("\t\t\t\t$('button[name=\"btnUpdate\"]').show();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tif (jqXHR.status != 0 && jqXHR.readyState != 0) {\r\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"관리자 정보 조회\", \"관리자 정보 조회 중 오류가 발생하였습니다.\", jqXHR.statusText + \"(\" + jqXHR.status + \")\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tupdateAdmin = function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar objAdminName = g_objAdminInfo.find('input[name=\"adminname\"]');\r\n");
      out.write("\t\tvar objEmail = g_objAdminInfo.find('input[name=\"email\"]');\r\n");
      out.write("\t\tvar objPhone = g_objAdminInfo.find('input[name=\"phone\"]');\r\n");
      out.write("\t\tvar objMobilePhone = g_objAdminInfo.find('input[name=\"mobilephone\"]');\r\n");
      out.write("\t\tvar objAdminType = g_objAdminInfo.find('input[name=\"admintype\"]');\r\n");
      out.write("\t\tvar objPasswordExpirationFlag = g_objAdminInfo.find('input[name=\"passwordexpirationflag\"]');\r\n");
      out.write("\t\tvar objPasswordExpirationPeriod = g_objAdminInfo.find('input[name=\"passwordexpirationperiod\"]');\r\n");
      out.write("\r\n");
      out.write("\t\tvar postData = getRequestUpdateAdminParam('");
      out.print((String)session.getAttribute("ADMINID"));
      out.write("',\r\n");
      out.write("\t\t\t'");
      out.print((String)session.getAttribute("ADMINID"));
      out.write("',\r\n");
      out.write("\t\t\tobjAdminName.val(),\r\n");
      out.write("\t\t\tobjEmail.val(),\r\n");
      out.write("\t\t\tobjPhone.val(),\r\n");
      out.write("\t\t\tobjMobilePhone.val(),\r\n");
      out.write("\t\t\tobjAdminType.val(),\r\n");
      out.write("\t\t\t'");
      out.print((String)session.getAttribute("COMPANYID"));
      out.write("',\r\n");
      out.write("\t\t\tobjPasswordExpirationFlag.val(),\r\n");
      out.write("\t\t\tobjPasswordExpirationPeriod.val());\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\turl: \"/CommandService\",\r\n");
      out.write("\t\t\tdata: $.param({sendmsg : postData}),\r\n");
      out.write("\t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t\tcache: false,\r\n");
      out.write("\t\t\t//async: false,\r\n");
      out.write("\t\t\tbeforeSend: function() {\r\n");
      out.write("\t\t\t\t$('.inner-center .ui-layout-content').block({ message: '<div style=\"height:20px;\"><img src=\"/images/processing.gif\" width=\"16\" height=\"16\" style=\"vertical-align: middle;\" /> <span style=\"position:relative; bottom: -1px;line-height: 20px;\">처리중...</span></div>', themedCSS: { margin: '0', padding: '0', 'min-width': '180px', 'width': '25%', height: '42px', backgroundColor: '#fff', border: '1px solid #aaa', color: '#fff', '-webkit-box-shadow': '4px 4px 4px 0px rgba(0,0,0,0.55)', '-moz-box-shadow': '4px 4px 4px 0px rgba(0,0,0,0.55)', 'box-shadow': '4px 4px 4px 0px rgba(0,0,0,0.55)' }, overlayCSS: { backgroundColor:'#000', opacity: .3, cursor: 'wait' }, fadeIn: 0, fadeOut: 0 });\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete: function(jqXHR, textStatus) {\r\n");
      out.write("\t\t\t\t$('.inner-center .ui-layout-content').unblock();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\tif ($(data).find('errorcode').text() != \"0000\") {\r\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"관리자 정보 변경\", \"관리자 정보 변경 중 오류가 발생하였습니다.\", $(data).find('errormsg').text());\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tdisplayInfoDialog(\"관리자 정보 변경\", \"정상 처리되었습니다.\", \"정상적으로 관리자 정보가 변경되었습니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tif (jqXHR.status != 0 && jqXHR.readyState != 0) {\r\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"관리자 정보 변경\", \"관리자 정보 변경 중 오류가 발생하였습니다.\", jqXHR.statusText + \"(\" + jqXHR.status + \")\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvalidateAdminData = function(mode) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar objAdminName = g_objAdminInfo.find('input[name=\"adminname\"]');\r\n");
      out.write("\t\tvar objEmail = g_objAdminInfo.find('input[name=\"email\"]');\r\n");
      out.write("\t\tvar objPhone = g_objAdminInfo.find('input[name=\"phone\"]');\r\n");
      out.write("\t\tvar objMobilePhone = g_objAdminInfo.find('input[name=\"mobilephone\"]');\r\n");
      out.write("\t\tvar objValidateTips = g_objAdminInfo.find('#validateTips');\r\n");
      out.write("\r\n");
      out.write("\t\tif (!isValidParam(objAdminName, PARAM_TYPE_NAME, \"관리자 명\", PARAM_NAME_MIN_LEN, PARAM_NAME_MAX_LEN, objValidateTips)) {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (objEmail.val().length > 0) {\r\n");
      out.write("\t\t\tif (!isValidParam(objEmail, PARAM_TYPE_EMAIL, \"이메일\", PARAM_EMAIL_MIN_LEN, PARAM_EMAIL_MAX_LEN, objValidateTips)) {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (objPhone.val().length > 0) {\r\n");
      out.write("\t\t\tif (!isValidParam(objPhone, PARAM_TYPE_PHONE, \"전화번호\", PARAM_PHONE_MIN_LEN, PARAM_PHONE_MAX_LEN, objValidateTips)) {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (objMobilePhone.val().length > 0) {\r\n");
      out.write("\t\t\tif (!isValidParam(objMobilePhone, PARAM_TYPE_MOBILE_PHONE, \"휴대전화번호\", PARAM_MOBILE_PHONE_MIN_LEN, PARAM_MOBILE_PHONE_MAX_LEN, objValidateTips)) {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t};\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"inner-center\"> \r\n");
      out.write("\t<div class=\"pane-header\">관리자 정보</div>\r\n");
      out.write("\t<div class=\"ui-layout-content\">\r\n");
      out.write("\t\t<div id=\"admin-info\" class=\"info-form show-block\">\r\n");
      out.write("\t\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t\t<ul class=\"infolist\">\r\n");
      out.write("\t\t\t\t\t<li><span class=\"required_field\">(*)</span> 필드는 필수 입력 필드입니다.</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"validateTips\" class=\"validateTips\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-message-holder\">\r\n");
      out.write("\t\t\t\t\t<div class=\"icon-holder\"><span id=\"alert-icon\" class=\"ui-icon ui-icon-alert\"></span></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"message-holder\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon-message\"><strong>입력오류:</strong>&nbsp;<span id=\"validateMsg\"></span></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-contents\">\r\n");
      out.write("\t\t\t\t<div id=\"row-adminid\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t\t<div class=\"field-title\">관리자 ID<span class=\"required_field\">*</span></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field-value\"><span id=\"adminid\">");
      out.print((String)session.getAttribute("ADMINID"));
      out.write("</span></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"row-adminname\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t\t<div class=\"field-title\">관리자 명<span class=\"required_field\">*</span></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field-value\"><input type=\"text\" id=\"adminname\" name=\"adminname\" class=\"text ui-widget-content\" /></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"row-email\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t\t<div class=\"field-title\">이메일</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field-value\"><input type=\"text\" id=\"email\" name=\"email\" class=\"text ui-widget-content\" /></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"row-phone\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t\t<div class=\"field-title\">전화번호</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field-value\"><input type=\"text\" id=\"phone\" name=\"phone\" class=\"text ui-widget-content\" /></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"row-mobilephone\" class=\"field-line\">\r\n");
      out.write("\t\t\t\t\t<div class=\"field-title\">휴대전화번호</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field-value\"><input type=\"text\" id=\"mobilephone\" name=\"mobilephone\" class=\"text ui-widget-content\" /></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"admintype\" name=\"admintype\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"passwordexpirationflag\" name=\"passwordexpirationflag\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"passwordexpirationperiod\" name=\"passwordexpirationperiod\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"pane-footer\">\r\n");
      out.write("\t\t<div class=\"button-line\">\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"btnChangePassword\" name=\"btnChangePassword\" class=\"normal-button\" style=\"display: none;\">비밀번호 변경</button>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"btnUpdate\" name=\"btnUpdate\" class=\"normal-button\" style=\"display: none;\">관리자 정보 수정</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- \t<div class=\"ui-layout-south\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t</div> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
