/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2021-08-05 01:27:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.SimpleDateFormat;
import com.spk.common.constant.CommonConstant;
import com.spk.error.*;
import com.spk.type.*;
import com.spk.util.Util;
import com.spk.util.DbUtil;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/dialog/confirm-dialog.jsp", Long.valueOf(1628122240000L));
    _jspx_dependants.put("/include/dialog/alert-dialog.jsp", Long.valueOf(1628122240000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	response.setHeader("Cache-Control","no-store");
	response.setHeader("Pragma","no-cache");
	response.setDateHeader ("Expires", 0);
	if (request.getProtocol().equals("HTTP/1.1")) {
		response.setHeader("Cache-Control","no-cache");
	}

	String oemString = "";
	String webTitleString = CommonConstant.SERVER_TITLE;
	String imageTitle = "main_logo_spk.png";
	/*************************************************************************
	 * 서버 설정 정보 조회
	 ************************************************************************/
	 HashMap<String, String> mapServerConfig = DbUtil.getServerConfig(session);
	if (!mapServerConfig.isEmpty()) {
		if ("MEDISAFER".equals(mapServerConfig.get("oem").toUpperCase())) {
			oemString = "MEDISAFER";
			webTitleString = CommonConstant.MEDISAFER_SERVER_TITLE;
			imageTitle = "main_logo_medisafer.png";

			/*****************************************************************
			 * 서비스 가능시간 검사
			 ****************************************************************/
			try {
				Date curDate = new Date();

				SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
				SimpleDateFormat datetimeFormat = new SimpleDateFormat("yyyyMMddHHmmss");

				curDate = datetimeFormat.parse(datetimeFormat.format(curDate));
				long curTime = curDate.getTime();
				Date beginServiceStopDate = datetimeFormat.parse(dateFormat.format(curDate) + "082000");
				long beginServiceStopTime = beginServiceStopDate.getTime();
				Date endServiceStopDate = datetimeFormat.parse(dateFormat.format(curDate) + "093000");
				long endServiceStopTime = endServiceStopDate.getTime();

				if ((curTime >= beginServiceStopTime) && (curTime <= endServiceStopTime)) { // 서비스 중지 시간
					response.sendRedirect("/login/login_wait.jsp");
				}
			} catch (Exception e) { }

		} else if ("BIZSAFER".equals(mapServerConfig.get("oem").toUpperCase())) {
			oemString = "BIZSAFER";
			webTitleString = CommonConstant.BIZSAFER_SERVER_TITLE;
			imageTitle = "main_logo_bizsafer.png";

			/*****************************************************************
			 * 서비스 가능시간 검사
			 ****************************************************************/
			try {
				Date curDate = new Date();

				SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
				SimpleDateFormat datetimeFormat = new SimpleDateFormat("yyyyMMddHHmmss");

				curDate = datetimeFormat.parse(datetimeFormat.format(curDate));
				long curTime = curDate.getTime();
				Date beginServiceStopDate = datetimeFormat.parse(dateFormat.format(curDate) + "082000");
				long beginServiceStopTime = beginServiceStopDate.getTime();
				Date endServiceStopDate = datetimeFormat.parse(dateFormat.format(curDate) + "093000");
				long endServiceStopTime = endServiceStopDate.getTime();

				if ((curTime >= beginServiceStopTime) && (curTime <= endServiceStopTime)) { // 서비스 중지 시간
					response.sendRedirect("/login/login_wait.jsp");
				}
			} catch (Exception e) { }

		}
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<meta http-equiv=\"Expires\" content=\"-1\" />\n");
      out.write("\t<meta http-equiv=\"Pragma\" content=\"no-cache\" />\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" content=\"No-Cache\" />\n");
      out.write("\t<title>");
      out.print(webTitleString);
      out.write("</title>\n");
      out.write("\n");
 if ("darkness".equals((String)session.getAttribute("THEMENAME"))) { 
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/darkness.css\" media=\"all\" />\n");
 } else { 
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/default.css\" media=\"all\" />\n");
 } 
      out.write('\n');
      out.write('\n');
 if ("darkness".equals((String)session.getAttribute("THEMENAME"))) { 
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/jquery-ui-1.10.3/themes/darkness/jquery.ui.all.css\" media=\"all\" />\n");
 } else { 
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/jquery-ui-1.10.3/css/custom-theme/jquery-ui-1.10.3.custom.css\" media=\"all\" />\n");
 } 
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery-ui-1.10.3/js/jquery-1.9.1.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t<!--\n");
      out.write("\tvar g_objDivMain;\n");
      out.write("\n");
      out.write("\t\t$(document).ready(function() {\n");
      out.write("\n");
      out.write("\t\t\tg_objDivMain = $('#div-main');\n");
      out.write("\n");
      out.write("\t\t\t// 뒤로가기 방지\n");
      out.write("\t\t\tif (window.history && window.history.pushState) {\n");
      out.write("\t\t\t\thistory.pushState(null, null, location.href);\n");
      out.write("\t\t\t\twindow.onpopstate = function () {\n");
      out.write("\t\t\t\t\thistory.go(1);\n");
      out.write("\t\t\t\t};\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t$(':input').keyup(function(event) {\n");
      out.write("\t\t\t\tif (event.which == 13) {\n");
      out.write("\t\t\t\t\t$('#btnLogin').click();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t$('#btnLogin').click(function() {\n");
      out.write("\t\t\t\tvar objAdminId = g_objDivMain.find('input[name=\"adminid\"]');\n");
      out.write("\t\t\t\tvar objPwd = g_objDivMain.find('input[name=\"pwd\"]');\n");
      out.write("\n");
      out.write("\t\t\t\tif (objAdminId.val() == \"\") {\n");
      out.write("\t\t\t\t\tobjAdminId.css(\"border-color\",\"#a0522d\");\n");
      out.write("\t\t\t\t\tobjAdminId.focus();\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"로그인\", \"ID를 입력해 주세요.\", null);\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tobjAdminId.css(\"border-color\",\"#dcdcdc\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tif (objPwd.val() == \"\") {\n");
      out.write("\t\t\t\t\tobjPwd.css(\"border-color\",\"#a0522d\");\n");
      out.write("\t\t\t\t\tobjPwd.focus();\n");
      out.write("\t\t\t\t\tdisplayAlertDialog(\"로그인\", \"비밀번호를 입력해 주세요.\", null);\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tobjPwd.css(\"border-color\",\"#dcdcdc\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tadminLogin(0);\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t$(\"#privacyhandlingpolicy\").click(function () {\n");
      out.write("\t\t\t\twindow.open(\"http://www.skbroadband.com/footer/Page.do?retUrl=/footer/PrivacyStatement\", \"_blank\", \"width=990,height=600,menubar=no,status=no,toolbar=no,scrollbars=yes\");\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\tadminLogin = function(forcedLoginFlag) {\n");
      out.write("\n");
      out.write("\t\t\t// request form serialize\n");
      out.write("\t\t\tvar formData = $('form[name=login-form]').serialize() + \"&forcedloginflag=\" + forcedLoginFlag + \"&admintype=\" + \"");
      out.print(AdminType.ADMIN_TYPE_COMPANY_ADMIN);
      out.write("\";\n");
      out.write("\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype: \"POST\",\n");
      out.write("\t\t\t\turl: \"/AdminLogin\",\n");
      out.write("\t\t\t\tdata: formData,\n");
      out.write("\t\t\t\tdataType: \"xml\",\n");
      out.write("\t\t\t\tcache: false,\n");
      out.write("\t\t\t\tasync: false,\n");
      out.write("\t\t\t\tsuccess: function(data, textStatus, jqXHR) {\n");
      out.write("\t\t\t\t\tif ($(data).find('errorcode').text() == \"0000\") {\n");
      out.write("\t\t\t\t\t\tlocation.href = \"/main.jsp\";\n");
      out.write("\t\t\t\t\t} else if ($(data).find('errorcode').text() == \"");
      out.print(CommonError.COMM_ERROR_ADMIN_ALREADY_LOGGED_ON);
      out.write("\") {\n");
      out.write("\t\t\t\t\t\tdisplayConfirmDialog(\"로그인\", $(data).find('errormsg').text() + \" 강제 로그인 하시겠습니까?\", \"\", function() { adminLogin(1); });\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\tdisplayAlertDialog(\"로그인\", \"로그인 중 오류가 발생하였습니다.\", $(data).find('errormsg').text());\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror: function(jqXHR, textStatus, errorThrown) {\n");
      out.write("\t\t\t\t\tif (jqXHR.status != 0 && jqXHR.readyState != 0) {\n");
      out.write("\t\t\t\t\t\tdisplayAlertDialog(\"로그인\", \"로그인 중 오류가 발생하였습니다.\", jqXHR.statusText + \"(\" + jqXHR.status + \")\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t};\n");
      out.write("\t//-->\n");
      out.write("\t</script>\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #1e1f23;\">\n");
      out.write("\t<div id=\"div-main\" class=\"centered-main\">\n");
      out.write("\t\t<div class=\"login-container\">\n");
      out.write("\t\t\t<div class=\"main_logo\"><img src=\"/images/");
      out.print(imageTitle);
      out.write("\" /></div>\n");
      out.write("\t\t\t<div style=\"margin-top: 55px;\">\n");
      out.write("\t\t\t\t<form id=\"login-form\" name=\"login-form\" method=\"post\" autocomplete=\"off\">\n");
      out.write("\t\t\t\t\t<div class=\"field-line\">\n");
      out.write("\t\t\t\t\t\t<div class=\"field-title\">ID</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"field-value\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"adminid\" name=\"adminid\" class=\"field-input\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"field-line\">\n");
      out.write("\t\t\t\t\t\t<div class=\"field-title\">PASSWORD</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"field-value\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" id=\"pwd\" name=\"pwd\" class=\"field-input\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"button-line\">\n");
      out.write("\t\t\t\t<input type=\"button\" id=\"btnLogin\" class=\"login-button\" value=\"LOGIN\" style=\"width: 370px;\"/>\n");
      out.write("\t\t\t</div>\n");
 if ("MEDISAFER".equals(oemString) || "BIZSAFER".equals(oemString)) { 
      out.write("\n");
      out.write("\t\t\t<div class=\"guide\">\n");
      out.write("\t\t\t\t<div id=\"privacyhandlingpolicy\" style=\"float:left; width: 50%; cursor: pointer;\">개인정보처리방침</div>\n");
      out.write("\t\t\t\t<div style=\"margin-left: 51%; text-align: right;\"><img src=\"/images/icon_callcenter.png\" style=\"height: 14px;\" /> 고객센터: 1670-4530</div>\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</div>\n");
 } 
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar g_objAlertDialog;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tg_objAlertDialog = $('#dialog-alert');\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.dialog({\r\n");
      out.write("\t\t\tautoOpen: false,\r\n");
      out.write("\t\t\tresizable: false,\r\n");
      out.write("\t\t\twidth: 500,\r\n");
      out.write("\t\t\theight: 'auto',\r\n");
      out.write("\t\t\tcloseOnEscape: false,\r\n");
      out.write("\t\t\tmodal: true,\r\n");
      out.write("\t\t\topen: function() {\r\n");
      out.write("\t\t\t\t$(this).parent().find('.ui-dialog-buttonpane button:contains(\"확인\")').button({\r\n");
      out.write("\t\t\t\t\ticons: { primary: 'ui-icon-circle-check' }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).parent().find(\".ui-dialog-titlebar-close\").hide();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbuttons: {\r\n");
      out.write("\t\t\t\t\"확인\": function() {\r\n");
      out.write("\t\t\t\t\t$(this).dialog('close');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tdisplayInfoDialog = function(dialogTitle, infoTitle, infoMessage) {\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-div').hasClass('ui-state-error')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-div').removeClass('ui-state-error').addClass('ui-state-highlight');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-icon').hasClass('ui-icon-alert')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-icon').removeClass('ui-icon-alert').addClass('ui-icon-info');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-title').html(infoTitle);\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-message').html(infoMessage);\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.dialog('option', 'title', dialogTitle);\r\n");
      out.write("\t\tg_objAlertDialog.dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdisplayAlertDialog = function(dialogTitle, alertTitle, alertMessage) {\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-div').hasClass('ui-state-highlight')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-div').removeClass('ui-state-highlight').addClass('ui-state-error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (g_objAlertDialog.find('#alert-icon').hasClass('ui-icon-info')) {\r\n");
      out.write("\t\t\tg_objAlertDialog.find('#alert-icon').removeClass('ui-icon-info').addClass('ui-icon-alert');\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-title').html(alertTitle);\r\n");
      out.write("\t\tg_objAlertDialog.find('#alert-message').html(alertMessage);\r\n");
      out.write("\r\n");
      out.write("\t\tg_objAlertDialog.dialog('option', 'title', dialogTitle);\r\n");
      out.write("\t\tg_objAlertDialog.dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"dialog-alert\" title=\"\" class=\"dialog-form\">\r\n");
      out.write("\t<div id=\"alert-div\" class=\"ui-state-highlight\" style=\"padding: 10px 10px 5px 10px;\">\r\n");
      out.write("\t\t<div class=\"icon-message-holder\">\r\n");
      out.write("\t\t\t<div class=\"icon-holder\"><span id=\"alert-icon\" class=\"ui-icon ui-icon-info\"></span></div>\r\n");
      out.write("\t\t\t<div class=\"message-holder\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-message\"><strong><span id=\"alert-title\"></span></strong></div>\r\n");
      out.write("\t\t\t\t<div class=\"detail-message\"><span id=\"alert-message\"></span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar g_objConfirmDialog;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tg_objConfirmDialog = $('#dialog-confirm');\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tdisplayConfirmDialog = function(dialogTitle, confirmTitle, confirmMessage, funcToExec) {\r\n");
      out.write("\t\tg_objConfirmDialog.dialog({\r\n");
      out.write("\t\t\tautoOpen: false,\r\n");
      out.write("\t\t\tresizable: false,\r\n");
      out.write("\t\t\twidth: 500,\r\n");
      out.write("\t\t\theight: 'auto',\r\n");
      out.write("\t\t\tcloseOnEscape: false,\r\n");
      out.write("\t\t\tmodal: true,\r\n");
      out.write("\t\t\topen: function() {\r\n");
      out.write("\t\t\t\t$(this).parent().find('.ui-dialog-buttonpane button:contains(\"확인\")').button({\r\n");
      out.write("\t\t\t\t\ticons: { primary: 'ui-icon-circle-check' }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).parent().find('.ui-dialog-buttonpane button:contains(\"취소\")').button({\r\n");
      out.write("\t\t\t\t\ticons: { primary: 'ui-icon-circle-close' }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).parent().find(\".ui-dialog-titlebar-close\").hide();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbuttons: {\r\n");
      out.write("\t\t\t\t\"확인\": function() {\r\n");
      out.write("\t\t\t\t\tfuncToExec();\r\n");
      out.write("\t\t\t\t\t$(this).dialog('close');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"취소\": function() {\r\n");
      out.write("\t\t\t\t\t$(this).dialog('close');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tg_objConfirmDialog.find('#confirm-title').html(confirmTitle);\r\n");
      out.write("\t\tg_objConfirmDialog.find('#confirm-message').html(confirmMessage);\r\n");
      out.write("\t\tg_objConfirmDialog.dialog('option', 'title', dialogTitle);\r\n");
      out.write("\r\n");
      out.write("\t\tg_objConfirmDialog.dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"dialog-confirm\" title=\"\" class=\"dialog-form\">\r\n");
      out.write("\t<div style=\"padding: 10px 10px 5px 10px;\">\r\n");
      out.write("\t\t<div class=\"icon-message-holder\">\r\n");
      out.write("\t\t\t<div class=\"icon-holder\"><span id=\"alert-icon\" class=\"ui-icon ui-icon-circle-check\"></span></div>\r\n");
      out.write("\t\t\t<div class=\"message-holder\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-message\"><strong><span id=\"confirm-title\"></span></strong></div>\r\n");
      out.write("\t\t\t\t<div class=\"detail-message\"><span id=\"confirm-message\"></span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
